import type { Metadata } from "next";
import "./globals.css";
import { Quicksand } from "next/font/google";
import { Providers } from "./providers";
import ErrorBoundary from "@/components/common/ErrorBoundary";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "justdoeet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} font-sans antialiased`}>
        <ErrorBoundary>
          <Providers>
            <main>{children}</main>
          </Providers>
        </ErrorBoundary>
      </body>
    </html>
  );
}
